<?php

/**
 * PlugintdArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class PlugintdArticle extends BasetdArticle
{
  /**
   * Returns short text of the article.
   *
   * @return String - short text.
   */
  public function getTextShort()
  {
    return mb_substr($this->getText(), 0, sfConfig::get('td_blog_short_text_sign_count')).'...';
  }

  /**
   * Activates the article.
   *
   * @return True
   */
  public function activate()
  {
    $this->setActive(true);
    $this->save();
    return true;
  }

  /**
   * Deactivates the article.
   *
   * @return True
   */
  public function deactivate()
  {
    $this->setActive(false);
    $this->save();
    return true;
  }
}